version: '3'
services:
  mysql:
    image: 'mysql:latest'
    container_name: bancosgp
    environment:
      - MYSQL_DATABASE=bancosgp
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    restart: always
    ports:
      - '3306:3306'
