CREATE TABLE IF NOT EXISTS USUARIO
(
    ID    INT         NOT NULL AUTO_INCREMENT,
    NOME  VARCHAR(80) NOT NULL,
    CPF   VARCHAR(11) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    ADMIN BOOLEAN     NOT NULL,
    PRIMARY KEY (ID)
)
