CREATE TABLE IF NOT EXISTS PROVA
(
    ID                   INT         NOT NULL AUTO_INCREMENT,
    TITULO               VARCHAR(80) NOT NULL,
    PERCENTUAL_APROVACAO INT         NOT NULL,
    PRIMARY KEY (ID)
)