CREATE TABLE IF NOT EXISTS AVALIACAO
(
    ID             INT  NOT NULL AUTO_INCREMENT,
    DATA_AVALIACAO DATE NOT NULL,
    APROVEITAMENTO INT  NOT NULL,
    ID_CANDIDATO   INT  NOT NULL,
    ID_PROVA       INT  NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CANDIDATO) REFERENCES USUARIO (ID),
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA (ID)
)
