CREATE TABLE IF NOT EXISTS PROVA_QUESTAO
(
    ID_PROVA   INT NOT NULL,
    ID_QUESTAO INT NOT NULL,
    PRIMARY KEY (ID_PROVA, ID_QUESTAO),
    FOREIGN KEY (ID_PROVA) REFERENCES PROVA (ID),
    FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTAO (ID)
)